# Generated by Django 2.1.7 on 2019-03-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floridalibrary', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
