# Generated by Django 2.1.7 on 2019-03-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floridalibrary', '0005_auto_20190311_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
    ]
