# Generated by Django 2.1.7 on 2019-03-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floridalibrary', '0006_auto_20190312_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
    ]
